version: '3'

services:
  node:
    build: .
    container_name: node-express-presentation
    command: bash -c "npm install && npm start"
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    working_dir: '/app'
    depends_on:
      - db
    links:
      - db

  db:
    image: 'mongo'
    container_name: mongo-express-presentation
